name: deploy_frontend
# Deploys when push is made from frontend folder

on:
  push:
    paths:
      - 'front_end/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Azure US Gov Cloud with CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureUSGovernment'
        enable-AzPSSession: false

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name frontendstorage --auth-mode key --connection-string 'DefaultEndpointsProtocol=https;AccountName=frontendstorage;AccountKey=iflO2/WbN/1oY4ZtsUaDLGcL0eNJ3uvoK7ngTSLazpeOGNQlGlPB/3JC7GPCqnwKMkAYUrypWo8f+AStcZ4d5w==;EndpointSuffix=core.usgovcloudapi.net' -d '$web' -s front_end/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "cdn-profile-alexmaccalman" --name "cdn-endpoint-alexmaccalman" --resource-group "front_end" --no-wait
    
  # Azure logout
    - name: logout
      run: |
        az logout
      if: always()